name: Build and Delivery

on:
  workflow_run:
    workflows: ["Test Python App"]
    branches: [main]
    types: [completed]

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # Явно указываем ветку

      - name: Verify files exist
        run: |
          echo "Checking critical files:"
          ls -la requirements.txt Dockerfile src/ tests/
          [ -f requirements.txt ] || exit 1
          [ -f Dockerfile ] || exit 1

      - name: Create build context archive
        run: |
          tar -czvf docker-context.tar.gz \
            requirements.txt \
            Dockerfile \
            src/ \
            tests/
          echo "Archive contents:"
          tar -tzvf docker-context.tar.gz

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push with clean context
        uses: docker/build-push-action@v4
        with:
          context: docker-context.tar.gz  # Используем архив как контекст
          file: Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest
          no-cache: true  # Полностью отключаем кэш
          build-args: |
            BUILDKIT_INLINE_CACHE=0  # Дополнительное отключение кэша

      - name: Cleanup
        run: rm -f docker-context.tar.gz