name: Build and Delivery

on:
  workflow_run:
    workflows: ["Test Python App"]
    branches: [main]  # Явно указываем main ветку
    types: [completed]

jobs:
  cd:
    runs-on: ubuntu-latest
    # Двойная проверка ветки
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # Принудительно используем main

      - name: Verify branch
        run: |
          echo "Current branch: ${{ github.event.workflow_run.head_branch }}"
          [ "${{ github.event.workflow_run.head_branch }}" == "main" ] || exit 1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest